(ns web.start-ui
  (:require
   [devcards.core :as dc]
   [marked :as marked]
   [web.date-picker]
   [web.text-editor]
   [web.text-field]
   [web.accordion]
   [web.autocomplete]
   [web.badge]
   [web.icon]
   [web.alert]
   [web.button]
   [web.skeleton]
   [web.switch]
   [web.checkbox]
   [web.select]
   [web.form-select]
   [web.toggle-button]
   [web.tooltip]
   [web.card]
   [web.typography]
   [web.grid]
   [web.click-away-listener]
   [web.link]
   [web.list]
   [web.menu]
   [web.icon-button]
   [web.dialog]
   [web.snackbar]
   [web.divider]
   [web.tabs]
   [web.floating-action-button]
   [web.radio]
   [web.box]
   [web.circular-progress]
   [web.linear-progress]
   [web.table]
   [web.timeline]
   [web.slide]
   [web.backdrop]
   [web.avatar]
   [web.drawer]
   [web.swipeable-drawer]
   [web.formatting]
   [web.tree-view]
   [web.zoom]
   [web.slider]
   [web.chip]
   [web.number-field]))

(js/goog.exportSymbol "DevcardsMarked" marked/marked)

(defn ^:export init []
  (dc/start-devcard-ui!))
