(ns web.devcards.start-ui
  (:require
   [cljsjs.react]
   [cljsjs.react.dom]
   [devcards.core :as dc]
   [marked :as marked]
   [web.devcards.date-picker]
   [web.devcards.text-editor]
   [web.devcards.text-field]
   [web.devcards.accordion]
   [web.devcards.autocomplete]
   [web.devcards.badge]
   [web.devcards.icon]
   [web.devcards.alert]
   [web.devcards.button]
   [web.devcards.skeleton]
   [web.devcards.switch]
   [web.devcards.checkbox]
   [web.devcards.select]
   [web.devcards.form-select]
   [web.devcards.toggle-button]
   [web.devcards.tooltip]
   [web.devcards.card]
   [web.devcards.typography]
   [web.devcards.grid]
   [web.devcards.click-away-listener]
   [web.devcards.link]
   [web.devcards.list]
   [web.devcards.menu]
   [web.devcards.icon-button]
   [web.devcards.dialog]
   [web.devcards.snackbar]
   [web.devcards.divider]
   [web.devcards.tabs]
   [web.devcards.floating-action-button]
   [web.devcards.radio]
   [web.devcards.box]
   [web.devcards.circular-progress]
   [web.devcards.linear-progress]
   [web.devcards.table]
   [web.devcards.timeline]
   [web.devcards.slide]
   [web.devcards.backdrop]
   [web.devcards.avatar]
   [web.devcards.drawer]
   [web.devcards.swipeable-drawer]
   [web.devcards.formatting]
   [web.devcards.tree-view]
   [web.devcards.zoom]))

(js/goog.exportSymbol "DevcardsMarked" marked/marked)

(defn ^:export init []
  (dc/start-devcard-ui!))
