name: clj-holmes

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: "30 19 * * 6"

jobs:
  clj-holmes:
    name: Run clj-holmes scanning
    runs-on: glms
    steps:
    - name: scan clojure
      uses: internal-marketplace/clj-scan@main